version: 0.1

phases:
  build:
    commands: >
      - lein uberjar && echo "{\"jar_file\": \"`ls target/uberjar/*.jar`\"}" > build.json

artifacts:
  files:
    - build.json
    - resources/cloud-formation/lambda-function.json
    - target/uberjar/*.jar
